### ISSUE TITLE
Password not working for PAGroup

### ISSUE THREAD

**Issue by panama63119** [PaloAltoNetworks/aws-transit-vpc#6]
Deploying these templates and PAGroup58 launches. However using the default password from the deployment document I cannot login. Also setting a new phash in the bootstrap file did not work as well. I am new to Palo Alto. If I look at the phash in the config, should it list more than an "*" 

admin@PA-VM# show mgt-config users
users {
  admin {
    phash *;
    permissions {
      role-based {
        superuser yes;

**Comment by jpeezus** [comment]
When you say default password are you using the password that we listed in the Transit VPC deployment guide?

**Comment by panama63119** [comment]
Yes.


Thomas Heljula
Sr. IT Administrator, Network
O: 314.770.3482

[cid:image005.png@01D3BF82.6016FF90]

[cid:image003.png@01D3BF82.5D26E480]

Best in KLAS for
Value-Based Care Managed
Services – two years running.

[cid:image004.png@01D3BF82.5D26E480]

13900 Riverport Drive, Maryland Heights, MO 63043

lumeris.com

**Comment by jpeezus** [comment]
For the sake of testing I would recommend to go back to the default bootstrap file
use the default credentials defined in the transit VPC guide
user is admin
password starts with a "R"

It does take some time for the PAGroup firewalls to be accessible via console but once they are are the default passord that starts with "R" will work. it's not the default admin/admin username and password but I am sure you are aware of that.

**Comment by panama63119** [comment]
If I created a new password and hash can I put that in the bootstrap.xml and use that password? I would like to avoid known default passwords.

Thomas Heljula
Sr. IT Administrator, Network
O: 314.770.3482

[cid:image005.png@01D3BF83.70E4A510]

[cid:image003.png@01D3BF83.6D268BA0]

Best in KLAS for
Value-Based Care Managed
Services – two years running.

[cid:image004.png@01D3BF83.6D268BA0]

13900 Riverport Drive, Maryland Heights, MO 63043

lumeris.com

**Comment by jpeezus** [comment]
yes as long as you bootstrap file in the S3 bucket matches the password in the stack deployment it should work. Can you provide detail on when you changed the password?
Did you launch the templates first then change the password?

**Comment by panama63119** [comment]
No I changed the bootstrap template first and then launched them in Cloudformation.


Thomas Heljula
Sr. IT Administrator, Network
O: 314.770.3482

[cid:image005.png@01D3BF8E.927A5BB0]

[cid:image003.png@01D3BF8E.90847F20]

Best in KLAS for
Value-Based Care Managed
Services – two years running.

[cid:image004.png@01D3BF8E.90847F20]

13900 Riverport Drive, Maryland Heights, MO 63043

lumeris.com

**Comment by panama63119** [comment]
So I believe that the step function is failing execution on creation of the Subscriber VPC and VPN.


3fa3e3a0-f3e3-46ed-a1d9-2ecaa2263b4d
arn:aws:states:us-west-2:167648698950:execution:SubscrierStateMachine-nWPliObOdMPh:3fa3e3a0-f3e3-46ed-a1d9-2ecaa2263b4d<https://us-west-2.console.aws.amazon.com/states/home?region=us-west-2#/executions/details/arn:aws:states:us-west-2:167648698950:execution:SubscrierStateMachine-nWPliObOdMPh:3fa3e3a0-f3e3-46ed-a1d9-2ecaa2263b4d>

Failed

Mar 19, 2018 02:52:57.875 PM

Mar 19, 2018 02:53:11.150 PM



10
LambdaFunctionScheduled
CreateVpnConnection     Lambda | CloudWatch logs          1143      Mar 19, 2018 02:52:59.018 PM
{
  "resource": "arn:aws:lambda:us-west-2:167648698950:function:createVpnConnection-INFRA-PaloAlto-Subscriber-VPC",
  "input": {
    "Action": "CreateVpnConnection",
    "VpcId": "vpc-35aed34c",
    "VpcCidr": "10.101.0.0/16",
    "Region": "us-west-2",
    "Rebalance": "False"
  },
  "timeoutInSeconds": null
}
11
LambdaFunctionStarted
CreateVpnConnection     Lambda | CloudWatch logs          1187      Mar 19, 2018 02:52:59.062 PM
{}
12
LambdaFunctionSucceeded
CreateVpnConnection     Lambda | CloudWatch logs          2870      Mar 19, 2018 02:53:00.745 PM
{
  "output": null
}
13
TaskStateExited
CreateVpnConnection     ---           2870      Mar 19, 2018 02:53:00.745 PM
{
  "name": "CreateVpnConnection",
  "output": null
}
14
TaskStateEntered
FetchFromSubscriberQueue         ---           2879      Mar 19, 2018 02:53:00.754 PM
{
  "name": "FetchFromSubscriberQueue",
  "input": null
}
15
LambdaFunctionScheduled
FetchFromSubscriberQueue         Lambda | CloudWatch logs          2879      Mar 19, 2018 02:53:00.754 PM
{
  "resource": "arn:aws:lambda:us-west-2:167648698950:function:fetchFromSubscriberQueueLambda-INFRA-PaloAlto-Subscriber-VPC",
  "input": null,
  "timeoutInSeconds": null
}
16
LambdaFunctionStarted
FetchFromSubscriberQueue         Lambda | CloudWatch logs          2917      Mar 19, 2018 02:53:00.792 PM
{}
17
LambdaFunctionSucceeded
FetchFromSubscriberQueue         Lambda | CloudWatch logs          13258    Mar 19, 2018 02:53:11.133 PM
{
  "output": null
}
18
TaskStateExited
FetchFromSubscriberQueue         ---           13258    Mar 19, 2018 02:53:11.133 PM
{
  "name": "FetchFromSubscriberQueue",
  "output": null
}
19
ChoiceStateEntered
ChoiceState        ---           13275    Mar 19, 2018 02:53:11.150 PM
{
  "name": "ChoiceState",
  "input": null
}
20
ExecutionFailed
---           13275    Mar 19, 2018 02:53:11.150 PM
{
  "error": "States.Runtime",
  "cause": "Internal Error (8b6bb8f7-a016-4752-be8a-ec4f70cc7127)"
}


Thomas Heljula
Sr. IT Administrator, Network
O: 314.770.3482

[cid:image006.png@01D3BF96.45FACBA0]

[cid:image003.png@01D3BF96.44232570]

Best in KLAS for
Value-Based Care Managed
Services – two years running.

[cid:image004.png@01D3BF96.44232570]

13900 Riverport Drive, Maryland Heights, MO 63043

lumeris.com

**Comment by narayan-iyengar** [comment]
I assume you have launched the initialize subscriber VPC template first?

Thanks,
--
/narayan

**Comment by panama63119** [comment]
Yes and the PAGroup has been created successfully as well.


Thomas Heljula
Sr. IT Administrator, Network
O: 314.770.3482

[cid:image006.png@01D3BF97.10E31200]

[cid:image003.png@01D3BF97.0E6B5B40]

Best in KLAS for
Value-Based Care Managed
Services – two years running.

[cid:image004.png@01D3BF97.0E6B5B40]

13900 Riverport Drive, Maryland Heights, MO 63043

lumeris.com

**Comment by narayan-iyengar** [comment]
ok...so you see firewalls but can't log into them, right?

The most common case for this that the bootstrapping has failed.
How are you updating the bootstrap file? 

As jpeezus points maybe you can try to deploy it without any changes first and then start updating bootstrap files?

**Comment by panama63119** [comment]
OK I am restoring the original bootstrap file and will attempt again.

Thomas Heljula
Sr. IT Administrator, Network
O: 314.770.3482

[cid:image006.png@01D3BF97.B59AE2F0]

[cid:image003.png@01D3BF97.B1FCFBB0]

Best in KLAS for
Value-Based Care Managed
Services – two years running.

[cid:image004.png@01D3BF97.B1FCFBB0]

13900 Riverport Drive, Maryland Heights, MO 63043

lumeris.com

**Comment by panama63119** [comment]
I restored the original bootstrap file and have redeployed the cloudformation templates. All of them have reported create_complete. The PAGroup exists and it appears to be build the VPN connection for the subscriber VPC. However the state machine for the subscriber is failing and reporting timeout.

[cid:image004.jpg@01D3C021.A0DDCAA0]

               15
LambdaFunctionScheduled
FetchFromSubscriberQueue         Lambda | CloudWatch logs          3036      Mar 20, 2018 07:48:31.666 AM
16
LambdaFunctionStarted
FetchFromSubscriberQueue         Lambda | CloudWatch logs          3064      Mar 20, 2018 07:48:31.694 AM
17
LambdaFunctionSucceeded
FetchFromSubscriberQueue         Lambda | CloudWatch logs          13465    Mar 20, 2018 07:48:42.095 AM
18
TaskStateExited
FetchFromSubscriberQueue         ---           13465    Mar 20, 2018 07:48:42.095 AM
19
ChoiceStateEntered
ChoiceState        ---           13481    Mar 20, 2018 07:48:42.111 AM
{
  "name": "ChoiceState",
  "input": null
}
20
ExecutionFailed
---           13481    Mar 20, 2018 07:48:42.111 AM
{
  "error": "States.Runtime",
  "cause": "Internal Error (b750782e-27f2-4c4c-a86e-e693ff664679)"
}

**Comment by panama63119** [comment]
Who is responsible for getting the “ConfigureSubscriberVpcVpn” action into the queue? That appears to be the next step and my state machine does not appear to be getting that message from the Lambda fetch. It is timing out. I see from the lamda documentation who starts the action, CloudTrailLambda, when it see the subscriberVpc=yes and send the Subscriber SNS the Action:CreateVpnConnection.

**Comment by cronq** [comment]
On the same topic, I've deployed this about 10 time with non-default CIDRs and it only worked once (the first time). What I was typically seeing was that a CheckVPN (sorry, I didn't document exactly) message was stuck in the SQS queue and just like panama, the FWs and VPNs were built, but it never loaded the bootstrap. Not sure that it's related, but I finally just used the default CIDRs last night and everything came up fine. No stuck message in SQS, BUT both of the step functions reported errors.

**Comment by panama63119** [comment]
I will give that a try.

**Comment by panama63119** [comment]
So I executed the templates with the default CIDRs and still cannot get beyond the subscriber CreateVpnConnection step. That step succeeds and pass the function back to Fetchfrom Queue. I assume the next message in the Queue that should be seen is ConfigureSubscriberVpcVpn action.

I subscribed to both Transit and Subscriber SNS queues. I do not receive any other message beyond that CreateVpnConnection action. Who delivers the next message to the queue for the step function to act on the ChoiceState?
